select id,id_menus,titulo from menus where (id_menus is null) limit 0,5;
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=21) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id,id_menus,titulo from menus where(id_menus=11) order by id asc;
select id,id_menus,titulo from menus where(id_menus=13) order by id asc;
select id,id_menus,titulo from menus where(id_menus=15) order by id asc;
select id,id_menus,titulo from menus where(id_menus=16) order by id asc;
select id,id_menus,titulo from menus where(id_menus=17) order by id asc;
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=1) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=2) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=3) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select count(paginas.id) as contador from paginas left join menus on(menus.id=paginas.id_menus) where(paginas.id_menus in(select id from menus where id_menus=11));
select paginas.id,paginas.id_menus,paginas.titulo,paginas.subtitulo,paginas.src,paginas.fonte,menus.titulo as menu from paginas left join menus on(menus.id=paginas.id_menus)  where(paginas.id_menus in(select id from menus where id_menus=11)) order by paginas.id desc  limit 0,9;
select paginas.id,paginas.id_menus,paginas.titulo,paginas.subtitulo,paginas.src,paginas.fonte,menus.titulo as menu from paginas left join menus on(menus.id=paginas.id_menus)  where(paginas.id_menus in(select id from menus where id_menus=13)) order by paginas.id desc  limit 0,9;
select paginas.id,paginas.id_menus,paginas.titulo,paginas.subtitulo,paginas.src,paginas.fonte,menus.titulo as menu from paginas left join menus on(menus.id=paginas.id_menus)  where(paginas.id_menus in(select id from menus where id_menus=15)) order by paginas.id desc  limit 0,9;
select distinct fotos.id,fotos.titulo,fotos.descricao,fotos.src, fotos.id_categoria, fotos.contador, categoriafotos.titulo as titulo_categoria from fotos left join categoriafotos on(fotos.id_categoria=categoriafotos.id)  order by fotos.id desc limit 0 ,05;
select categoriafotos.id,categoriafotos.titulo,(select f1.src from fotos f1 where((select max(f2.id) from fotos f2 where(id_categoria=categoriafotos.id))=f1.id)) as src from categoriafotos  order by categoriafotos.id desc limit 0,5;
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=19) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=22) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=23) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=24) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=5) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=6) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=7) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=8) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=9) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=10) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=11) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=12) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=13) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=14) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=15) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=16) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=17) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id, titulo,id_paginas,id_menus,id_tipo,src,url,popup from patrocinio  where (patrocinio.id_tipo=17) and (patrocinio.id_menus is null)and(patrocinio.id_paginas is null);
select id,id_menus,ip,data_cadastro from contagem order by id desc;
select id,id_menus,titulo from menus where (id_menus is null) limit 0,5;